config/routes.rb
Rails.application.routes.draw do
  get '/simluator' => 'prices#simluator'
  get '/result' => 'prices#result'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/price.rb
class Price < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  def simluator
    @price = Price.new
  end

  def result
    @start_day_at = start_day_at
    @finish_day_at = finish_day_at
    # 何分差があるか
    use = (finish_day_at - start_day_at).to_i / 60 # /60で秒換算を分換算に変更
    if params[:grade] == "BASIC"
      @time = (use /15) * 250
      @time = 4290 if use <= 360 && @time > 4290 #6時間まで
      @time = 6490 if use <= 720 && @time > 6490 #12時間まで
      @time = 8690 if use <= 1440 && @time > 8690 #24時間まで
      @time = 11990 if use <= 2160 && @time > 11990 #36時間まで
      @time = 14190 if use <= 2880 && @time > 14190 #48時間まで
      @time = 20240 if use <= 4320 && @time > 20240 #72時間まで
    elsif params[:grade] == "MIDDLE"
      @time = (use /15) * 350
      @time = 6490 if use <= 360 && @time > 6490 #6時間まで
      @time = 8690 if use <= 720 && @time > 8690 #12時間まで
      @time = 11990 if use <= 1440 && @time > 11990 #24時間まで
      @time = 16390 if use <= 2160 && @time > 16390 #36時間まで
      @time = 19690 if use <= 2880 && @time > 19690 #48時間まで
      @time = 28490 if use <= 4320 && @time > 28490 #72時間まで
    else
      @time = (use /15) * 460
      @time = 8690 if use <= 360 && @time > 8690 #6時間まで
      @time = 13090 if use <= 720 && @time > 13090 #12時間まで
      @time = 18590 if use <= 1440 && @time > 18590 #24時間まで
      @time = 25190 if use <= 2160 && @time > 25190 #36時間まで
      @time = 30690 if use <= 2880 && @time > 30690 #48時間まで
      @time = 43890 if use <= 4320 && @time > 43890 #72時間まで
    end
  end

  private

  def start_day_at
    y = params["start_day_at(1i)"].to_i
    m = params["start_day_at(2i)"].to_i
    d = params["start_day_at(3i)"].to_i
    h = params["start_day_at(4i)"].to_i
    min = params["start_day_at(5i)"].to_i
    Time.local(y, m, d, h, min)
  end

  def finish_day_at
    y = params["finish_day_at(1i)"].to_i
    m = params["finish_day_at(2i)"].to_i
    d = params["finish_day_at(3i)"].to_i
    h = params["finish_day_at(4i)"].to_i
    min = params["finish_day_at(5i)"].to_i
    Time.local(y, m, d, h, min)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlacoleAssessment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <div class="mx-auto" style="width: 800px;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/prices/result.html.erb
<div class="car">
  <br class="d-none d-sm-block">
  <h1 class="text-dark">シミュレーション結果</h1>
  <br class="d-none d-sm-block">
  <h4 class="text-dark">
    <%= "#{@start_day_at.strftime("%Y年%m月%d日 %H:%M")}から"%>
    <br class="d-none d-sm-block">
    <%= "#{@finish_day_at.strftime("%Y年%m月%d日 %H:%M")}のご利用金額は" %>
    <br class="d-none d-sm-block">
  </h4>
  <h2 class="text-dark">
    <br class="d-none d-sm-block">
    <%= "#{@time.to_s(:delimited)}円です" %>
  </h2>
  <br class="d-none d-sm-block">
  <br class="d-none d-sm-block">
  <br class="d-none d-sm-block">
</div>

app/views/prices/simluator.html.erb
<div class="car">
  <br class="d-none d-sm-block">
  <h1 class="text-dark">カーシェアリング料金シミュレーション</h1>

  <%= form_with(url: result_path, method: :get, local: true) do |f| %>
    <div class="form-group">
      <br class="d-none d-sm-block">
      <%= f.label :grade, :グレード %>
      <%= f.collection_select :grade, Price.all, :grade, :grade %>
    </div>

    <div class="form-group">
      <%= f.label :start_day_at, :いつから %>
      <%= f.datetime_select :start_day_at, date_separator: '/', use_month_numbers: true, :minute_step => 15,:default => Time.now + 1.hours %>
    </div>

    <div class="form-group">
      <%= f.label :finish_day_at, :いつまで %>
      <%= f.datetime_select :finish_day_at, date_separator: '/', use_month_numbers: true, :minute_step => 15,:default => Time.now + 1.hours %>
    </div>

    <br class="d-none d-sm-block">
    <%= f.submit :シミュレーションする, class: 'btn btn-primary' %>
  <% end %>
  <br class="d-none d-sm-block">
</div>